name: opencode-docker
services:
  ts-sidecar:
    image: tailscale/tailscale:latest
    hostname: opencode
    environment:
      - TS_AUTHKEY=${TAILSCALE_AUTHKEY} #Generate in Tailscale Admin Console
      - TS_STATE_DIR=/var/lib/tailscale
    volumes:
      - tailscale-data:/var/lib/tailscale
      - /dev/net/tun:/dev/net/tun
    cap_add:
      - net_admin
      - sys_module
    restart: unless-stopped

  opencode:
    build: .
    container_name: opencode
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities:
                - gpu
    restart: unless-stopped
    network_mode: service:ts-sidecar
    environment:
      - TZ=Asia/Manila
      - USER_PASSWORD=${USER_PASSWORD}
    volumes:
      - ./workspace:/home/ubuntu/workspace
      - ./config/opencode:/home/ubuntu/.config/opencode
      - ./config/nvim:/home/ubuntu/.config/nvim

    logging:
      options:
        max-size: "10m"
        max-file: "3"
    depends_on:
      - ts-sidecar

volumes:
  tailscale-data:


