name: opencode-docker
services:
  ts-sidecar:
    image: tailscale/tailscale:latest
    hostname: opencode
    environment:
      - TS_AUTHKEY=tskey-auth-kPnASMci2D11CNTRL-kx2QfEZyeDc51TsdMSZ5Ec4tZ7hK98yjK # Generate in Admin Console
      - TS_STATE_DIR=/var/lib/tailscale
    volumes:
      - tailscale-data:/var/lib/tailscale
      - /dev/net/tun:/dev/net/tun
    cap_add:
      - net_admin
      - sys_module
    restart: unless-stopped

  opencode:
    image: rpfilomeno/opencode:latest
    container_name: opencode
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities:
                - gpu
    restart: unless-stopped
    network_mode: service:ts-sidecar
    environment:
      - TZ=Asia/Manila
      - USER_PASSWORD=123456
    volumes:
      - D:\Github\opencode-docker\workspace:/home/workspace

    logging:
      options:
        max-size: "10m"
        max-file: "3"
    depends_on:
      - ts-sidecar

volumes:
  tailscale-data:

